#!/usr/bin/env bash

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Use scp to transfer the file to the server's home directory
scp -i "$4" "$1" "$3@$2":~/

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
