#!/usr/bin/env bash

# Check if the correct number of parameters is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$4" "$1" "$3@$2":~/
