#!/usr/bin/env bash

# Install Nginx using apt-get with '-y' flag for automatic confirmation
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
