#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection by modifying the Nginx configuration
sudo sed -i '/location \/ {/a \ \ \ \ location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
