#!/bin/bash

# Display listening TCP ports
echo "Listening TCP ports:"
netstat -tln | grep '^tcp' | awk '{print $4, $NF}' | sed 's/:::/\*/' | sed 's/::1:/localhost:/'

# Display listening UDP ports
echo "Listening UDP ports:"
netstat -uln | grep '^udp' | awk '{print $4, $NF}' | sed 's/:::/\*/' | sed 's/::1:/localhost:/'
