#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds between each iteration
# it responds to the SIGTERM signal by echoing "I am invincible!!!"

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
