#!/usr/bin/env bash
# This script displays the content of the current directory (excluding hidden files) in a list format, showing only the part of the name after the first dash

for file in *
do
    if [ -f "$file" ] && [[ $file != .* ]]  # Check if file is a regular file and not a hidden file
    then
        filename=$(echo "$file" | cut -d '-' -f 2-)  # Extract the part of the name after the first dash
        echo "$filename"
    fi
done
