#!/usr/bin/env bash
# This script provides information about the school file

file="school"

if [ -e "$file" ]; then  # Check if the file exists
    echo "$file file exists"
    
    if [ -s "$file" ]; then  # Check if the file is not empty
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
    
    if [ -f "$file" ]; then  # Check if the file is a regular file
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
