#!/usr/bin/env bash
# This script gives information about the school file

if [ -e "school" ]; then
    if [ -f "school" ]; then
        if [ -s "school" ]; then
            echo "school file exists"
        else
            echo "school file exists"
            echo "school file is empty"
        fi
        echo "school is a regular file"
    else
        echo "school exists but it's a directory"
    fi
else
    echo "school doesn't exist"
fi
