#!/usr/bin/env bash
# Reset ufw to default settings
sudo ufw reset

# Allow all outgoing traffic by default
sudo ufw default allow  outgoing

# Deny all incoming traffic by default
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

sudo ufw status verbose
